spring.application.name=Springboot Web Tutorial
spring.h2.console.enabled=true
spring.datasource.url = jdbc:h2:file:/Users/vinay/OneDrive/Documents/springBootWebTutorial/db
spring.datasource.username=vinayDB
spring.datasource.password=vinay123
spring.jpa.hibernate.ddl-auto=update